# -*- coding: utf-8 -*-
"""替代收据凭证 PDF(ใบแทนใบเสร็จ / 收据替代凭证 · doc 14 §7)。

无正式票时由记账草稿生成的费用凭证。复用泰/中/英混排字体(usage_report_pdf_text._register_fonts·
฿ 已覆盖)。纯渲染叶子:输入已组好的 dict,不连库。中泰双语标题 + 字段。
"""

from __future__ import annotations

import io
from decimal import Decimal

_TITLE = "ใบแทนใบเสร็จ / 收据替代凭证 / Receipt Voucher"


def _money(v) -> str:
    try:
        return f"{Decimal(str(v if v not in (None, '') else 0)):,.2f}"
    except Exception:
        return str(v or "-")


def build_receipt_pdf(fields: dict) -> bytes:
    """费用字段 dict → ใบแทนใบเสร็จ PDF bytes(A5)。

    fields 键(都可选,空显示 -):business_name / doc_date / vendor_name / vendor_tax_id /
    amount / vat_amount / wht_amount / expense_type / category / subcategory / invoice_number / note。
    """
    from reportlab.lib.pagesizes import A5
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    from services.usage.usage_report_pdf_text import _register_fonts

    base, bold = _register_fonts()
    f = fields or {}
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A5)
    w, h = A5

    y = h - 18 * mm
    c.setFont(bold, 13)
    c.drawCentredString(w / 2, y, _TITLE)
    y -= 6 * mm
    c.setLineWidth(0.5)
    c.line(15 * mm, y, w - 15 * mm, y)
    y -= 9 * mm

    def row(label: str, value) -> None:
        nonlocal y
        c.setFont(base, 10)
        c.drawString(18 * mm, y, label)
        c.setFont(bold if label.startswith("จำนวนเงิน") else base, 10)
        c.drawString(60 * mm, y, str(value) if value not in (None, "") else "-")
        y -= 7 * mm

    cur = f.get("currency") or "THB"
    row("ธุรกิจ / 业务主体", f.get("business_name"))
    row("วันที่ / 日期", f.get("doc_date"))
    row("ผู้ขาย / 卖家", f.get("vendor_name"))
    row("เลขผู้เสียภาษี / 税号", f.get("vendor_tax_id"))
    row("เลขที่เอกสาร / 单据号", f.get("invoice_number"))
    row("หมวดหมู่ / 分类", f.get("category"))
    row("หมวดย่อย / 子分类", f.get("subcategory"))
    et = {"goods": "สินค้า/商品", "service": "บริการ/服务"}.get(f.get("expense_type") or "", "")
    row("ประเภท / 类型", et)
    y -= 2 * mm
    c.line(15 * mm, y, w - 15 * mm, y)
    y -= 8 * mm
    row("VAT", _money(f.get("vat_amount")) if f.get("vat_amount") else "-")
    row("หัก ณ ที่จ่าย / 预扣", _money(f.get("wht_amount")) if f.get("wht_amount") else "-")
    row(f"จำนวนเงินรวม / 总额 ({cur})", _money(f.get("amount")))
    y -= 4 * mm
    if f.get("note"):
        c.setFont(base, 9)
        c.drawString(18 * mm, y, f"หมายเหตุ / 备注: {f.get('note')}"[:60])
        y -= 8 * mm

    c.setFont(base, 7)
    c.drawString(
        18 * mm,
        15 * mm,
        "Generated by Pearnly · เอกสารนี้ใช้แทนใบเสร็จกรณีไม่มีใบกำกับภาษี",
    )
    c.showPage()
    c.save()
    return buf.getvalue()
