# -*- coding: utf-8 -*-
"""report_engine · 报表模板定义(REPORT_TEMPLATES)data leaf。"""

REPORT_TEMPLATES = {
    # ----- 模板 1 · ภ.พ.30 进项税明细(法定 · 默认) -----
    "input_vat": {
        "code": "input_vat",
        "name_key": "tpl-input-vat",
        "desc_key": "tpl-input-vat-desc",
        "category_key": "tpl-cat-tax",
        "title_key": "tpl-input-vat-title",
        "recommended": True,
        "show_info_block": True,  # 顶部信息块(公司名 / 税号 / 月份 / 共 X 张)
        "show_summary_sheet": True,  # 第二 Sheet 汇总
        "show_signature_block": True,  # 底部签名栏
        "freeze_panes": "A4",  # 冻结到信息块下面
        "columns": [
            {"key": "no", "header_key": "col-no", "width": 6, "align": "center", "type": "int"},
            {
                "key": "invoice_date",
                "header_key": "col-invoice-date",
                "width": 12,
                "align": "center",
                "type": "date",
            },
            {
                "key": "invoice_no",
                "header_key": "col-invoice-no",
                "width": 18,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_name",
                "header_key": "col-seller-name",
                "width": 32,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_tax_id",
                "header_key": "col-seller-tax-id",
                "width": 18,
                "align": "center",
                "type": "tax_id",
            },
            {
                "key": "seller_branch",
                "header_key": "col-seller-branch",
                "width": 14,
                "align": "center",
                "type": "branch",
            },
            {
                "key": "amount_before_vat",
                "header_key": "col-amount-before-vat",
                "width": 14,
                "align": "right",
                "type": "money",
            },
            {
                "key": "vat_amount",
                "header_key": "col-vat-amount",
                "width": 12,
                "align": "right",
                "type": "money",
            },
            {
                "key": "total_amount",
                "header_key": "col-total-amount",
                "width": 14,
                "align": "right",
                "type": "money",
            },
            {
                "key": "category",
                "header_key": "col-category",
                "width": 12,
                "align": "center",
                "type": "text",
            },
            {
                "key": "source",
                "header_key": "col-source",
                "width": 10,
                "align": "center",
                "type": "source",
            },
        ],
        "total_columns": ["amount_before_vat", "vat_amount", "total_amount"],
    },
    # ----- 模板 2 · 标准明细(老板 / 内部审核) -----
    "standard": {
        "code": "standard",
        "name_key": "tpl-standard",
        "desc_key": "tpl-standard-desc",
        "category_key": "tpl-cat-internal",
        "title_key": "tpl-standard-title",
        "recommended": False,
        "show_info_block": True,
        "show_summary_sheet": True,
        "show_signature_block": False,
        "freeze_panes": "A4",
        "auto_filter": True,  # 列首加 Excel 自动筛选
        "warn_amount_threshold": 500000,  # 大额警告阈值
        "columns": [
            {"key": "no", "header_key": "col-no", "width": 6, "align": "center", "type": "int"},
            {
                "key": "invoice_date",
                "header_key": "col-invoice-date",
                "width": 12,
                "align": "center",
                "type": "date",
            },
            {
                "key": "invoice_no",
                "header_key": "col-invoice-no",
                "width": 18,
                "align": "left",
                "type": "text",
            },
            {
                "key": "filename",
                "header_key": "col-filename",
                "width": 22,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_name",
                "header_key": "col-seller-name",
                "width": 30,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_tax_id",
                "header_key": "col-seller-tax-id",
                "width": 18,
                "align": "center",
                "type": "tax_id",
            },
            {
                "key": "amount_before_vat",
                "header_key": "col-amount-before-vat",
                "width": 14,
                "align": "right",
                "type": "money",
            },
            {
                "key": "vat_amount",
                "header_key": "col-vat-amount",
                "width": 12,
                "align": "right",
                "type": "money",
            },
            {
                "key": "total_amount",
                "header_key": "col-total-amount",
                "width": 14,
                "align": "right",
                "type": "money",
            },
            {
                "key": "category",
                "header_key": "col-category",
                "width": 12,
                "align": "center",
                "type": "text",
            },
            {
                "key": "source",
                "header_key": "col-source",
                "width": 10,
                "align": "center",
                "type": "source",
            },
            {
                "key": "notes",
                "header_key": "col-notes",
                "width": 20,
                "align": "left",
                "type": "text",
            },
        ],
        "total_columns": ["amount_before_vat", "vat_amount", "total_amount"],
    },
    # ----- 模板 3 · ERP 录入格式(数据导向) -----
    "erp": {
        "code": "erp",
        "name_key": "tpl-erp",
        "desc_key": "tpl-erp-desc",
        "category_key": "tpl-cat-erp",
        "title_key": "tpl-erp-title",
        "recommended": False,
        "show_info_block": False,  # ERP 不要装饰
        "show_summary_sheet": False,
        "show_signature_block": False,
        "freeze_panes": "A2",
        "ascii_only": True,  # 列名严格 ASCII
        "iso_date": True,  # 日期 ISO 格式
        "no_thousand_sep": True,  # 金额不带千位分隔
        "first_row_marker": "<!-- ERP_IMPORT_FORMAT_v1 · Pearnly -->",
        "columns": [
            {
                "key": "invoice_date",
                "header_key": "col-invoice-date",
                "header_ascii": "Date",
                "width": 12,
                "align": "center",
                "type": "date_iso",
            },
            {
                "key": "invoice_no",
                "header_key": "col-doc-no",
                "header_ascii": "DocNo",
                "width": 18,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_name",
                "header_key": "col-vendor-name",
                "header_ascii": "VendorName",
                "width": 30,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_tax_id",
                "header_key": "col-vendor-tax",
                "header_ascii": "VendorTaxID",
                "width": 16,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_branch",
                "header_key": "col-seller-branch",
                "header_ascii": "Branch",
                "width": 12,
                "align": "center",
                "type": "branch_code",
            },
            {
                "key": "amount_before_vat",
                "header_key": "col-net-amount",
                "header_ascii": "NetAmount",
                "width": 12,
                "align": "right",
                "type": "money_raw",
            },
            {
                "key": "vat_amount",
                "header_key": "col-vat-amount",
                "header_ascii": "VAT",
                "width": 12,
                "align": "right",
                "type": "money_raw",
            },
            {
                "key": "total_amount",
                "header_key": "col-total-amount",
                "header_ascii": "TotalAmount",
                "width": 12,
                "align": "right",
                "type": "money_raw",
            },
            {
                "key": "category",
                "header_key": "col-category",
                "header_ascii": "Category",
                "width": 12,
                "align": "left",
                "type": "text",
            },
        ],
        "total_columns": [],  # ERP 不要合计行
    },
    # ----- 模板 4 · 凭证装订清单(打印) -----
    "print": {
        "code": "print",
        "name_key": "tpl-print",
        "desc_key": "tpl-print-desc",
        "category_key": "tpl-cat-print",
        "title_key": "tpl-print-title",
        "recommended": False,
        "show_info_block": True,
        "show_summary_sheet": False,
        "show_signature_block": True,
        "freeze_panes": "A4",
        "row_height": 32,  # 行高大 · 签名空间
        "page_setup": "A4_landscape",
        "columns": [
            {"key": "no", "header_key": "col-no", "width": 6, "align": "center", "type": "int"},
            {
                "key": "invoice_date",
                "header_key": "col-invoice-date",
                "width": 14,
                "align": "center",
                "type": "date",
            },
            {
                "key": "invoice_no",
                "header_key": "col-invoice-no",
                "width": 22,
                "align": "left",
                "type": "text",
            },
            {
                "key": "seller_name",
                "header_key": "col-seller-name",
                "width": 36,
                "align": "left",
                "type": "text",
            },
            {
                "key": "total_amount",
                "header_key": "col-total-amount",
                "width": 16,
                "align": "right",
                "type": "money",
            },
            {
                "key": "signature",
                "header_key": "col-signature",
                "width": 20,
                "align": "center",
                "type": "blank",
            },
        ],
        "total_columns": ["total_amount"],
    },
}
