"""Localized, user-facing explanations for Cowork LINE ERP preflight states."""

from __future__ import annotations

REASONS = {
    "th": {
        "workspace_unbound": "ยังไม่ได้ผูกชุดบัญชี กรุณาตั้งค่าบนเว็บไซต์",
        "workspace_binding_conflict": "การผูกชุดบัญชีซ้ำ กรุณาตรวจสอบบนเว็บไซต์",
        "endpoint_disabled": "การเชื่อมต่อถูกปิด กรุณาเปิดใช้งานบนเว็บไซต์",
        "endpoint_revoked": "การเชื่อมต่อหมดอายุ กรุณาเชื่อมต่อใหม่",
        "credentials_missing": "ข้อมูลบัญชี ERP ไม่ครบ กรุณาตั้งค่าใหม่",
        "companion_offline": "Pearnly Companion ออฟไลน์ กรุณาเปิดบนคอมพิวเตอร์",
        "companion_not_ready": "Pearnly Companion ยังไม่พร้อม กรุณาตรวจสอบการเชื่อมต่อ",
        "profile_unconfirmed": "Pearnly Companion ยังไม่ได้ยืนยันชุดบัญชี",
        "profile_mismatch": "ชุดบัญชีใน Companion ไม่ตรงกับการตั้งค่าบนเว็บไซต์",
        "account_set_locked": "Express กำลังใช้งานชุดบัญชี กรุณาปิด Express หรือรอสักครู่",
        "workspace_subject_missing": "ไม่พบข้อมูลบริษัทในเอกสาร",
        "workspace_lookup_failed": "ตรวจสอบบริษัทไม่สำเร็จ กรุณาลองอีกครั้ง",
        "workspace_ambiguous": "พบหลายบริษัท กรุณาเลือกชุดบัญชีในหน้าแก้ไข",
        "workspace_subject_unmatched": "บริษัทในเอกสารยังไม่ตรงกับชุดบัญชี",
        "workspace_subject_mismatch": "บริษัทในเอกสารไม่ตรงกับชุดบัญชีที่เลือก",
        "posting_kind_required": "กรุณาเลือกสินค้าในสต๊อกหรือบริการ",
        "posting_kind_invalid": "ประเภทสินค้าไม่ถูกต้อง กรุณาเลือกใหม่",
        "payment_required": "กรุณาเลือกเงินสดหรือเครดิต",
        "payment_invalid": "วิธีชำระเงินไม่ถูกต้อง กรุณาเลือกใหม่",
        "express_disabled": "Express ยังไม่พร้อมรับเอกสาร",
        "endpoint_not_found": "ไม่พบการเชื่อมต่อ ERP กรุณาเลือกใหม่",
    },
    "zh": {
        "workspace_unbound": "尚未映射账套，请到网页端配置",
        "workspace_binding_conflict": "账套映射冲突，请到网页端检查",
        "endpoint_disabled": "ERP 连接已停用，请到网页端启用",
        "endpoint_revoked": "ERP 连接已失效，请重新连接",
        "credentials_missing": "ERP 账号配置不完整，请重新配置",
        "companion_offline": "Pearnly 小助手离线，请在电脑上启动",
        "companion_not_ready": "Pearnly 小助手尚未就绪，请检查连接",
        "profile_unconfirmed": "小助手尚未确认该账套",
        "profile_mismatch": "小助手账套与网页配置不一致",
        "account_set_locked": "Express 正在使用该账套，请关闭 Express 或稍后再试",
        "workspace_subject_missing": "单据中缺少公司信息",
        "workspace_lookup_failed": "公司匹配失败，请稍后重试",
        "workspace_ambiguous": "匹配到多个公司，请在编辑器选择账套",
        "workspace_subject_unmatched": "单据公司尚未匹配到账套",
        "workspace_subject_mismatch": "单据公司与所选账套不一致",
        "posting_kind_required": "请选择库存商品或服务",
        "posting_kind_invalid": "商品类型无效，请重新选择",
        "payment_required": "请选择现金或赊账",
        "payment_invalid": "付款方式无效，请重新选择",
        "express_disabled": "Express 当前无法接收单据",
        "endpoint_not_found": "ERP 连接不存在，请重新选择",
    },
    "en": {
        "workspace_unbound": "No account set mapping. Configure it on the website.",
        "workspace_binding_conflict": "Account set mapping conflict. Check it on the website.",
        "endpoint_disabled": "ERP connection is disabled. Enable it on the website.",
        "endpoint_revoked": "ERP connection expired. Reconnect it.",
        "credentials_missing": "ERP credentials are incomplete. Configure them again.",
        "companion_offline": "Pearnly Companion is offline. Start it on the computer.",
        "companion_not_ready": "Pearnly Companion is not ready. Check the connection.",
        "profile_unconfirmed": "The account set has not been confirmed in Companion.",
        "profile_mismatch": "Companion account set does not match the website setting.",
        "account_set_locked": "Express is using this account set. Close Express or try later.",
        "workspace_subject_missing": "Company information is missing from the document.",
        "workspace_lookup_failed": "Company matching failed. Try again.",
        "workspace_ambiguous": "Multiple companies matched. Choose an account set in the editor.",
        "workspace_subject_unmatched": "The document company is not mapped to an account set.",
        "workspace_subject_mismatch": "The document company does not match the selected account set.",
        "posting_kind_required": "Choose inventory or service.",
        "posting_kind_invalid": "Invalid item type. Choose again.",
        "payment_required": "Choose cash or credit.",
        "payment_invalid": "Invalid payment method. Choose again.",
        "express_disabled": "Express is not ready to receive documents.",
        "endpoint_not_found": "ERP connection not found. Choose again.",
    },
    "ja": {
        "workspace_unbound": "帳簿が未連携です。ウェブ画面で設定してください。",
        "workspace_binding_conflict": "帳簿の連携が重複しています。ウェブ画面で確認してください。",
        "endpoint_disabled": "ERP 接続が停止中です。ウェブ画面で有効にしてください。",
        "endpoint_revoked": "ERP 接続の有効期限が切れました。再接続してください。",
        "credentials_missing": "ERP アカウント設定が不完全です。再設定してください。",
        "companion_offline": "Pearnly Companion がオフラインです。PC で起動してください。",
        "companion_not_ready": "Pearnly Companion の接続を確認してください。",
        "profile_unconfirmed": "Companion で帳簿が未確認です。",
        "profile_mismatch": "Companion の帳簿がウェブ設定と一致しません。",
        "account_set_locked": "Express が帳簿を使用中です。閉じるか後でもう一度お試しください。",
        "workspace_subject_missing": "書類に会社情報がありません。",
        "workspace_lookup_failed": "会社の照合に失敗しました。もう一度お試しください。",
        "workspace_ambiguous": "複数の会社が一致しました。編集画面で帳簿を選択してください。",
        "workspace_subject_unmatched": "書類の会社が帳簿に連携されていません。",
        "workspace_subject_mismatch": "書類の会社と選択した帳簿が一致しません。",
        "posting_kind_required": "在庫商品またはサービスを選択してください。",
        "posting_kind_invalid": "商品種別が無効です。選び直してください。",
        "payment_required": "現金または掛けを選択してください。",
        "payment_invalid": "支払方法が無効です。選び直してください。",
        "express_disabled": "Express は現在書類を受信できません。",
        "endpoint_not_found": "ERP 接続が見つかりません。選び直してください。",
    },
}


def reason_text(lang: str, code: str) -> str:
    selected = lang if lang in REASONS else "th"
    return REASONS[selected].get(code, "")


__all__ = ["reason_text"]
