"""Field order and localized labels used by the Cowork LINE review card."""

HEADER_KEYS = (
    "invoice_number",
    "date",
    "document_type",
    "seller_name",
    "seller_tax",
    "seller_branch",
    "seller_address",
    "buyer_name",
    "buyer_tax",
    "buyer_branch",
    "buyer_address",
    "subtotal",
    "discount",
    "vat",
    "wht_amount",
    "total_amount",
    "currency",
    "payment_method",
    "notes",
)

HEADER_LABELS = {
    "th": (
        "เลขที่เอกสาร",
        "วันที่",
        "ประเภทเอกสาร",
        "ผู้ขาย",
        "เลขภาษีผู้ขาย",
        "สาขาผู้ขาย",
        "ที่อยู่ผู้ขาย",
        "ผู้ซื้อ",
        "เลขภาษีผู้ซื้อ",
        "สาขาผู้ซื้อ",
        "ที่อยู่ผู้ซื้อ",
        "ก่อนภาษี",
        "ส่วนลด",
        "VAT",
        "หัก ณ ที่จ่าย",
        "ยอดรวม",
        "สกุลเงิน",
        "การชำระเงิน",
        "หมายเหตุ",
    ),
    "zh": (
        "单据号码",
        "日期",
        "单据类型",
        "卖方",
        "卖方税号",
        "卖方分店",
        "卖方地址",
        "买方",
        "买方税号",
        "买方分店",
        "买方地址",
        "未税金额",
        "折扣",
        "增值税",
        "预扣税",
        "总金额",
        "币种",
        "付款方式",
        "备注",
    ),
    "en": (
        "Invoice no.",
        "Date",
        "Document type",
        "Seller",
        "Seller tax ID",
        "Seller branch",
        "Seller address",
        "Buyer",
        "Buyer tax ID",
        "Buyer branch",
        "Buyer address",
        "Subtotal",
        "Discount",
        "VAT",
        "WHT",
        "Total",
        "Currency",
        "Payment",
        "Notes",
    ),
    "ja": (
        "書類番号",
        "日付",
        "書類種別",
        "売り手",
        "売り手税番号",
        "売り手支店",
        "売り手住所",
        "買い手",
        "買い手税番号",
        "買い手支店",
        "買い手住所",
        "小計",
        "割引",
        "VAT",
        "源泉税",
        "合計",
        "通貨",
        "支払方法",
        "備考",
    ),
}

__all__ = ["HEADER_KEYS", "HEADER_LABELS"]
