# -*- coding: utf-8 -*-
"""
Pearnly · 通用导入器 · 表头同义词词典(REFACTOR-WA-B1 · 2026-05-29 从 template_learning 抽出)

纯搬家 0 逻辑改 · 叶子模块(纯数据 · 无 import · 防循环)。
statement 列推断(template_learning)+ GL 列推断(gl_inference)共用这套多语(泰/中/英/越/日)同义词。
比 bank_recon_v2 现有词典更全 · 学习层专用。
"""

DATE_H = {
    "วันที่",
    "วัน",
    "วันที่ทำรายการ",
    "วันที่เอกสาร",
    "date",
    "trans date",
    "transaction date",
    "posting date",
    "value date",
    "日期",
    "交易日",
    "交易日期",
    "记账日期",
    "ngày",
    "取引日",
}
DESC_H = {
    "รายการ",
    "รายละเอียด",
    "รายละเอียดรายการ",
    "description",
    "detail",
    "details",
    "particulars",
    "narration",
    "memo",
    "remark",
    "remarks",
    "note",
    "摘要",
    "描述",
    "交易摘要",
    "备注",
    "摘要说明",
    "diễn giải",
    "摘要・備考",
}
DEPOSIT_H = {
    "รายรับ",
    "รับ",
    "เงินรับ",
    "ฝากเงิน",
    "ฝาก",
    "เงินฝาก",
    "deposit",
    "deposits",
    "credit",
    "credit amount",
    "cr",
    "income",
    "receipt",
    "receipts",
    "in",
    "paid in",
    "money in",
    "存款",
    "存入",
    "入账",
    "收入",
    "贷方",
    "贷方金额",
    "gửi",
    "入金",
}
WITHDRAWAL_H = {
    "รายจ่าย",
    "จ่าย",
    "เงินจ่าย",
    "ถอนเงิน",
    "ถอน",
    "เงินถอน",
    "withdrawal",
    "withdrawals",
    "debit",
    "debit amount",
    "dr",
    "expense",
    "payment",
    "payments",
    "out",
    "paid out",
    "money out",
    "取款",
    "支取",
    "出账",
    "支出",
    "借方",
    "借方金额",
    "rút",
    "出金",
}
BALANCE_H = {
    "ยอดคงเหลือ",
    "คงเหลือ",
    "ยอด",
    "balance",
    "running balance",
    "closing balance",
    "available balance",
    "余额",
    "结余",
    "账户余额",
    "số dư",
    "残高",
}
AMOUNT_H = {
    "amount",
    "จำนวนเงิน",
    "จำนวน",
    "net amount",
    "金额",
    "金額",
    "số tiền",
    "金额(±)",
}
# GL 总账专用(借/贷/凭证/科目)· 借≈取(debit) 贷≈存(credit)
GL_DEBIT_H = {"เดบิต", "เดบิท", "debit", "debit amount", "dr", "借方", "借方金额", "ถอน", "จ่าย"}
GL_CREDIT_H = {"เครดิต", "credit", "credit amount", "cr", "贷方", "贷方金额", "ฝาก", "รับ"}
GL_DOC_H = {
    "เลขที่เอกสาร",
    "เอกสาร",
    "ใบสำคัญ",
    "doc",
    "doc no",
    "doc_no",
    "document no",
    "voucher",
    "voucher no",
    "reference",
    "ref",
    "凭证号",
    "凭证",
    "单据号",
}
GL_ACCOUNT_H = {
    "รหัสบัญชี",
    "เลขที่บัญชี",
    "บัญชี",
    "รหัส",
    "account",
    "account code",
    "account no",
    "acct",
    "gl account",
    "科目",
    "科目代码",
    "账号",
    "会计科目",
}
