"""关系域稳定错误码。"""


class EngagementError(ValueError):
    def __init__(self, code: str):
        super().__init__(code)
        self.code = code


FIRM_REQUIRED = "ERR_FIRM_REQUIRED"
FIRM_INACTIVE = "ERR_FIRM_INACTIVE"
PRIMARY_EXISTS = "ERR_PRIMARY_ENGAGEMENT_EXISTS"
NOT_ACTIVE = "ERR_ENGAGEMENT_NOT_ACTIVE"
WORKSPACE_MISMATCH = "ERR_ENGAGEMENT_WORKSPACE_MISMATCH"
FORBIDDEN = "ERR_ENGAGEMENT_FORBIDDEN"
