const labels: Record<string, string[]> = {
    autoNumber: ['สร้างเมื่อบันทึก', 'Assigned on save', '保存时自动生成', '保存時に自動採番'],
    number: ['เลขที่', 'Number', '单号', '伝票番号'],
    date: ['วันที่', 'Date', '日期', '日付'],
    branch: ['สาขา', 'Branch', '分支', '支店'],
    credit: ['เครดิต', 'Credit days', '账期（天）', '支払猶予日数'],
    due: ['ครบกำหนด', 'Due date', '到期日', '支払期日'],
    rate: ['อัตราภาษี', 'Tax rate (%)', '税率（%）', '税率（%）'],
    department: ['แผนก', 'Department', '部门', '部門'],
    project: ['งาน', 'Project', '项目', '案件'],
    employee: ['พนักงาน', 'Employee', '经办人', '担当者'],
    salesperson: ['พนักงานขาย', 'Salesperson', '销售员', '営業担当'],
    delivery: ['กำหนดส่งสินค้า', 'Delivery date', '交货日期', '納期'],
    transferred: ['โอนข้อมูล', 'Data transferred', '转入标记', '転記済み'],
    cash: ['เงินสด', 'Cash', '现金', '現金'],
    supplierCode: ['รหัสผู้จำหน่าย', 'Supplier code', '供应商编码', '仕入先コード'],
    supplier: ['ชื่อผู้จำหน่าย', 'Supplier name', '供应商名称', '仕入先名'],
    customerCode: ['รหัสลูกค้า', 'Customer code', '客户编码', '顧客コード'],
    customer: ['ชื่อลูกค้า', 'Customer name', '客户名称', '顧客名'],
    billSupplier: ['รหัสผู้จำหน่าย (บิล)', 'Bill supplier code', '票据供应商编码', '請求元コード'],
    billCustomer: ['รหัสลูกค้า (บิล)', 'Bill customer code', '票据客户编码', '請求先コード'],
    bill: ['เลขที่บิล', 'Bill number', '票据号', '請求書番号'],
    area: ['พื้นที่การขาย', 'Sales area', '销售区域', '販売地域'],
    transport: ['ประเภทขนส่ง', 'Transport type', '运输类型', '配送方法'],
    data: ['ข้อมูล', 'Details', '资料', '明細'],
    units: ['หน่วยนับ', 'Units', '计量单位', '単位'],
    deposit: ['เงินมัดจำ', 'Deposit', '定金', '前払金'],
    cheque: ['เช็คจ่าย', 'Cheques', '付款支票', '支払小切手'],
    withholding: ['ภาษีหัก ณ ที่จ่าย', 'Withholding tax', '预扣税', '源泉税'],
    payment: ['รับชำระหนี้', 'Payment details', '收款资料', '入金情報'],
    files: ['ไฟล์', 'Files', '附件', '添付'],
    row: ['ลำดับ', 'No.', '序号', '番号'],
    code: ['รหัสสินค้า', 'Product code', '商品编码', '商品コード'],
    name: ['ชื่อสินค้า', 'Product name', '商品名称', '商品名'],
    warehouse: ['คลัง', 'Warehouse', '仓库', '倉庫'],
    qty: ['จำนวน', 'Quantity', '数量', '数量'],
    unit: ['หน่วย', 'Unit', '单位', '単位'],
    price: ['ราคา/หน่วย', 'Unit price', '单价', '単価'],
    amount: ['จำนวนเงิน', 'Amount', '金额', '金額'],
    remove: ['ลบ', 'Delete', '删除', '削除'],
    add: ['เพิ่มรายการ', 'Add line', '添加一行', '行を追加'],
    notes: ['หมายเหตุ', 'Notes', '备注', '備考'],
    gross: ['ยอดรวม', 'Total', '合计', '合計'],
    discount: ['หัก ส่วนลด', 'Less discount', '减：折扣', '値引'],
    lessDeposit: ['หัก เงินมัดจำ', 'Less deposit', '减：定金', '前払金控除'],
    base: ['ยอดรวมก่อนภาษี', 'Before tax', '税前金额', '税抜金額'],
    vat: ['ภาษี', 'Tax', '税额', '税額'],
    net: ['ยอดสุทธิ', 'Net total', '净额', '総額'],
    chequeTotal: ['รวมเช็คจ่าย', 'Cheque total', '支票合计', '小切手合計'],
    interest: ['ดอกเบี้ยเงินกู้ธนาคาร', 'Bank interest', '银行利息', '銀行利息'],
    receivedDiscount: ['ส่วนลดรับ', 'Discount received', '获得折扣', '受取割引'],
    withheld: [
        'ภาษีเงินได้หัก ณ ที่จ่ายค้าง',
        'Withholding outstanding',
        '待扣缴税额',
        '未納源泉税',
    ],
    paid: ['รวมจ่ายชำระ', 'Total payment', '付款合计', '支払合計'],
    choose: ['เลือกไฟล์', 'Choose file', '选择文件', 'ファイルを選択'],
    taxId: ['เลขประจำตัวผู้เสียภาษี', 'Tax ID', '税号', '納税番号'],
    back: ['กลับ', 'Back', '返回', '戻る'],
    purchase: ['บันทึกซื้อ', 'Purchase', '采购记录', '仕入'],
    sales: ['บันทึกขาย', 'Sales', '销售记录', '売上'],
};
export function manualLabel(key: string, lang: string): string {
    return (
        labels[key]?.[({ th: 0, en: 1, zh: 2, ja: 3 } as Record<string, number>)[lang] ?? 0] || key
    );
}
