# -*- coding: utf-8 -*-
"""
Pearnly · DAL facade re-export(REFACTOR-WA-B2)

各业务域 DAL(services/*/store.py 等)集中到此,供 db.py 末尾一行
`from services.dal_reexports import *` 桥回 db 命名空间 —— 所有历史 db.xxx()
调用点零改动。db.py 自身只保留连接池 / get_cursor / RLS 基础设施(铁律 #26 硬线 #1)。

_REEXPORTS:域模块路径 → 对外 re-export 名清单。元素为 str = 同名 re-export;
为 (源名, 导出名) 元组 = 重命名 re-export。__all__ 末尾按清单动态构建
(含下划线私有 helper · import * 据此带出 · 对象身份与源模块一致)。
新增/删除 DAL:只改本字典。
"""

import importlib

_REEXPORTS = {
    "services.sales.schema": [
        "ensure_sales_rls",
    ],
    "services.knowledge.rules_dal": [
        "ensure_client_rules_rls",
    ],
    "services.automation.schema": [
        "ensure_automation_rls",
    ],
    "services.etax.schema": [
        "ensure_etax_rls",
    ],
    "services.knowledge.risk_check": [
        "ensure_risk_check_rls",
    ],
    "services.knowledge.rls": [
        "ensure_knowledge_rls",
    ],
    "services.erp.credentials_rls": [
        "ensure_erp_credentials_rls",
    ],
    "services.settings_misc.schema": [
        "ensure_settings_misc_rls",
    ],
    "services.email_ingest.store": [
        "get_email_account",
        "get_email_account_safe",
        "upsert_email_account",
        "delete_email_account",
        "list_enabled_email_accounts",
        "update_email_account_status",
        "insert_email_ingest_log",
        "list_email_ingest_logs",
        "is_email_uid_seen",
        "mark_email_uid_seen",
        "ensure_email_ingest_rls",
    ],
    "services.erp.mappings_store": [
        "ensure_erp_mapping_tables",
        "list_erp_client_mappings",
        "upsert_erp_client_mapping",
        "delete_erp_client_mapping",
        "list_erp_account_mappings",
        "upsert_erp_account_mapping",
        "delete_erp_account_mapping",
        "list_erp_tax_mappings",
        "upsert_erp_tax_mapping",
        "delete_erp_tax_mapping",
        "list_erp_product_mappings",
        "upsert_erp_product_mapping",
        "delete_erp_product_mapping",
        "find_erp_product_mappings_batch",
        "get_mrerp_mappings_bundle",
    ],
    "services.notification.store": [
        "ensure_notification_tables",
        "list_notification_rules",
        "get_notification_rule",
        "create_notification_rule",
        "update_notification_rule",
        "delete_notification_rule",
        "log_notification",
        "list_notification_logs",
        "list_active_notification_rules_by_template",
    ],
    "services.erp.push_store": [
        "ERP_MAX_RETRIES",
        "USER_DATA_ERROR_CODES",
        "USER_DATA_ERROR_THAI_PATTERNS",
        "list_erp_endpoints",
        "get_erp_endpoint",
        "get_default_erp_endpoint",
        "create_erp_endpoint",
        "update_erp_endpoint",
        "delete_erp_endpoint",
        "insert_push_log",
        "has_recent_successful_push",
        "update_endpoint_stats",
        "update_history_push_status",
        "ensure_erp_endpoints_adapter_constraint",
        "ensure_erp_push_logs_adapter_constraint",
        "ensure_erp_push_logs_status_constraint",
        "ensure_erp_retry_columns",
        "ensure_erp_push_rls",
        "ensure_single_express_endpoint",
        "is_user_data_error",
        "is_already_pushed_error",
        "classify_push_status",
        "counts_as_endpoint_success",
        "get_erp_retry_delay_sec",
        "schedule_log_retry",
        "clear_retry_schedule",
        "list_logs_due_for_retry",
        "increment_retry_count",
        "update_log_status_after_retry",
        "delete_push_logs",
        "list_push_logs",
        "get_push_log_detail",
        "get_push_stats_today",
        "classify_push_exception",
    ],
    "services.recon.bank_recon_v2_store": [
        "ensure_bank_recon_v2_table",
        "create_bank_recon_v2_task",
        "get_bank_recon_v2_task",
        "list_bank_recon_v2_tasks",
        "delete_bank_recon_v2_task",
        "delete_bank_recon_v2_tasks_batch",
    ],
    "services.recon.gl_vat_store": [
        "ensure_gl_vat_task_table",
        "create_gl_vat_task",
        "get_gl_vat_task",
        "list_gl_vat_tasks",
        "delete_gl_vat_task",
        "delete_gl_vat_tasks_batch",
    ],
    "services.recon.vat_recon_tasks_store": [
        "ensure_vat_recon_tasks_table",
        "create_vat_recon_task",
        "list_vat_recon_tasks",
        "get_vat_recon_task",
        "delete_vat_recon_task",
        "delete_vat_recon_tasks_older_than",
        "get_vat_recon_tasks_kpi",
    ],
    "services.recon.bank_recon_v1_store": [
        "ensure_bank_recon_client_id_column",
        "ensure_bank_recon_rls",
        "create_bank_recon_session",
        "save_bank_recon_parse",
        "mark_recon_parse_failed",
        "get_bank_recon_session",
        "list_bank_recon_sessions",
        "update_bank_recon_session_client",
        "get_bank_recon_stats",
        "list_bank_recon_transactions",
        "delete_bank_recon_session",
        "find_invoice_candidates_for_tx",
        "save_match_result",
        "get_tx_candidates",
        "update_session_match_stats",
        "override_tx_match",
    ],
    "services.audit.store": [
        "insert_operation_log",
        "list_operation_logs",
        "list_operation_logs_paged",
    ],
    "services.recon.vat_recon_store": [
        "ensure_vat_recon_tables",
        "create_vat_report",
        "get_vat_report",
        "create_recon_task",
        "get_recon_task",
        "update_recon_task_status",
        "update_recon_task_completed",
        "list_recon_tasks",
        "bulk_insert_recon_rows",
        "list_recon_rows",
        "list_invoices_for_recon",
        "find_client_by_tax_id",
        "auto_create_client",
        "get_recon_row",
        "update_recon_row_ai_analysis",
        "update_recon_row_action",
        "list_recon_rows_detailed",
        "get_client_by_id",
        "find_or_create_client_by_tax_id",
    ],
    "services.archive.store": [
        "ensure_archive_settings_table",
        "get_archive_settings",
        "get_archive_template",
        "upsert_archive_settings",
    ],
    "services.rd.store": ["get_rd_daily_usage", "increment_rd_daily_usage"],
    "services.cost.store": [
        "ensure_ocr_cost_log_table",
        "log_ocr_cost",
        "get_cost_overview",
        "get_cost_by_user",
        "get_cost_daily_trend",
        "get_cost_daily_by_engine",
    ],
    "services.exceptions.store": [
        "ensure_exceptions_tables",
        "is_exception_whitelisted",
        "insert_exception",
        "list_exceptions",
        "get_exception",
        "resolve_exception",
        "add_exception_whitelist",
        "list_exception_whitelist",
        "delete_exception_whitelist",
        "delete_pending_exceptions_by_history",
        "count_exceptions_by_status_and_rule",
        "count_whitelist_rules",
        "batch_resolve_exceptions",
    ],
    "services.billing.store": ["ensure_billing_balance_table", "get_latest_balance"],
    "services.clients.store": [
        "ensure_clients_table",
        "ensure_supplier_categories_table",
        "get_category_for_seller",
        "ensure_buyer_to_client_table",
        "learn_buyer_to_client",
        "try_resolve_buyer_to_client",
        "resolve_or_create_buyer_client",
        "update_history_client_id",
        "upsert_supplier_category",
        "list_used_categories",
        "count_supplier_mappings",
        "list_clients",
        "get_client",
        "create_client",
        "update_client",
        "delete_client",
        "assign_invoice_to_client",
    ],
    "services.workspace.store": [
        "ensure_workspace_tables",
        "create_workspace_client",
        "tax_id_in_use",
        "get_workspace_client",
        "list_workspace_clients",
        "list_workspace_clients_enriched",
        "update_workspace_client",
        "archive_workspace_client",
        "bind_workspace_endpoint",
        "get_workspace_endpoint_id",
        "match_workspace_for_seller",
        "update_history_workspace_client_id",
        "ensure_seller_route_table",
        "learn_seller_workspace_route",
    ],
    # 仅 db 门面用、不经 store 透传的 → 直接从定义模块取(store.py 已贴 500 行上限,不再加透传)。
    "services.workspace.seller_routing": [
        "route_assigns_workspace",
        "match_workspace_for_buyer",
    ],
    "services.membership.store": [
        "get_visible_client_ids_for_user",
        "list_assignments_by_employees",
        "set_employee_assignments",
        "auto_assign_client_to_creator",
        "get_user_tenant_id",
        "migrate_to_membership_model",
        "list_orphan_users",
        "fix_orphan_users",
        "backfill_tenant_ids",
    ],
    "services.tenant.store": [
        "get_tenant",
        "get_user_tenant",
        "list_all_tenants",
        "create_tenant",
        "update_tenant_quota",
        "update_tenant_status",
        "get_tenant_monthly_usage",
        "increment_tenant_monthly_usage",
        "list_tenant_members",
        "get_tenant_usage_summary",
        "list_all_owner_users",
        "create_owner_user",
        "preview_owner_cascade",
        "delete_owner_user_cascade",
        "list_user_companies",
        "set_user_active_tenant",
    ],
    "services.user_settings.store": [
        "get_user_dup_check_enabled",
        "set_user_dup_check_enabled",
        "set_user_gemini_key",
        "get_user_gemini_key",
        "get_user_gemini_key_masked",
        "update_user_preferred_lang",
    ],
    "services.ocr.feedback.schema": [
        "ensure_ocr_feedback_table",
    ],
    "services.ocr_history.store": [
        "list_ocr_history",
        "get_ocr_history_detail",
        "update_ocr_history_pages",
        "commit_staged_ocr_history",
        "delete_ocr_history",
        "delete_ocr_history_with_pdf_paths",
        "insert_ocr_history",
        "update_ocr_history_pdf_storage",
        "update_history_official_name",
        "get_history_pdf_info",
        "find_ocr_by_hash",
        "check_duplicate_invoice",
        "_extract_summary_fields",
    ],
    "services.line_binding.store": [
        "generate_line_binding_code",
        "consume_line_binding_code",
        "create_or_update_line_binding",
        "get_line_binding_by_user",
        "get_user_by_line_user_id",
        "unbind_line_by_user",
        "unbind_line_by_line_user_id",
        "ensure_line_binding_rls",
    ],
    "services.credits.store": [
        "get_credits_revenue_overview",
        "get_tenants_credits_summary",
        "get_tenant_credit_summary",
        "get_credits_daily_trend",
    ],
    "services.billing.pricing": [
        "estimate_pdf_cost_thb",
        "estimate_excel_cost_thb",
        "PDF_TIER1_LIMIT_V21",
        "PDF_TIER1_PRICE_V21",
        "PDF_TIER2_PRICE_V21",
        "EXCEL_CHARS_PER_SATANG_V21",
        "EXCEL_SATANG_PRICE_V21",
        "SUBSCRIPTION_PLANS",
        "SUBSCRIPTION_CYCLE_DAYS",
        "subscription_plan_spec",
        "doc_quota_pages",
    ],
    "services.billing.subscription": [
        "get_active_subscription",
        "consume_subscription_quota",
        "overage_cost",
        "subscription_subscribe",
        "subscription_cancel",
        "subscription_catalog",
    ],
    "services.auth.user_lookup": [
        "find_user_by_username",
        "find_user_by_id",
        "find_user_by_id_cached",
        "evict_user_cache",
        "find_user_by_google_sub",
        "link_google_sub_to_user",
        "update_user_avatar",
        "find_user_by_line_uid",
        "link_line_uid_to_user",
    ],
    "services.auth.password": ["verify_user_password", "reset_user_password"],
    "services.auth.account_merge": [
        "is_line_placeholder_username",
        "update_user_email_and_username",
        "merge_line_account_into_existing",
    ],
    "services.usage.store": [
        "update_last_login",
        "increment_user_monthly_usage",
        "cleanup_expired_history",
    ],
    "services.billing.account_status": [
        "is_user_billing_exempt",
        "get_billing_status_combined",
        "_bkk_year_month",
        ("_EXEMPT_CACHE", "_EXEMPT_CACHE_V21"),
    ],
    "services.billing.charge": ["charge_ocr", "_excel_char_count_estimate", "charge_ocr_async"],
    "services.billing.credits_schema": ["ensure_credits_tables", "ensure_tenant_credits"],
    "services.membership.schema": ["ensure_membership_tables"],
    "services.users.columns": [
        "ensure_google_sub_column",
        "ensure_password_changed_at_column",
        "ensure_line_uid_column",
    ],
    "services.auth.email_codes_schema": ["ensure_email_codes_table"],
}

__all__ = []
for _module_path, _entries in _REEXPORTS.items():
    _mod = importlib.import_module(_module_path)
    for _entry in _entries:
        _src, _dst = _entry if isinstance(_entry, tuple) else (_entry, _entry)
        globals()[_dst] = getattr(_mod, _src)
        __all__.append(_dst)
