export type ErpTeamCopy = Record<string, string>;

const COPY: Record<string, ErpTeamCopy> = {
    th: {
        nav: 'จัดการทีม',
        title: 'จัดการทีม ERP',
        subtitle: 'เชิญพนักงานและกำหนดสิทธิ์ตามหน้าที่',
        invite: 'เชิญสมาชิก',
        seats: 'ที่นั่ง',
        sharedQuota: 'เครดิต OCR ใช้ร่วมกันทั้งร้านและเจ้าของเป็นผู้เติมเงิน',
        loading: 'กำลังโหลดสมาชิก…',
        emptyTitle: 'ยังไม่มีสมาชิก',
        emptyBody: 'เพิ่มพนักงานซื้อหรือขายคนแรกของคุณ',
        error: 'โหลดข้อมูลไม่สำเร็จ',
        retry: 'ลองอีกครั้ง',
        account: 'บัญชี Pearnly',
        password: 'รหัสผ่าน Pearnly',
        modules: 'ฟังก์ชันที่อนุญาต',
        product: 'สินค้า',
        purchase: 'ซื้อ',
        sales: 'ขาย',
        erp: 'ERP ที่ใช้ร่วมกัน',
        none: 'ยังไม่ส่ง ERP',
        existing: 'การเชื่อมต่อของเจ้าของ',
        newMrerp: 'เพิ่มบัญชี MR.ERP',
        mrUser: 'ชื่อผู้ใช้ MR.ERP',
        mrPass: 'รหัสผ่าน MR.ERP',
        expressHelp:
            'Express ใช้การแมปชุดบัญชีจาก Pearnly Companion จึงไม่มีชื่อผู้ใช้หรือรหัสผ่าน',
        noExpress: 'เจ้าของต้องเชื่อมต่อ Express และสแกนชุดบัญชีใน Companion ก่อน',
        cancel: 'ยกเลิก',
        create: 'สร้างสมาชิก',
        creating: 'กำลังสร้าง…',
        active: 'ใช้งาน',
        inactive: 'ปิดใช้งาน',
        save: 'บันทึกสิทธิ์',
        saved: 'บันทึกแล้ว',
        lineBound: 'เชื่อมต่อ LINE แล้ว',
        lineUnbound: 'ยังไม่เชื่อมต่อ LINE',
        bindLine: 'เชื่อมต่อ LINE',
        unbind: 'ยกเลิกการเชื่อมต่อ',
        erpConnected: 'ใช้ {name}',
        erpNone: 'ไม่ส่ง ERP',
        lastLogin: 'เข้าสู่ระบบล่าสุด',
        never: 'ยังไม่เคย',
        lineTitle: 'ให้สมาชิกเชื่อมต่อ LINE ของตนเอง',
        lineStep1: 'สแกน QR เพื่อเพิ่ม Pearnly ERP เป็นเพื่อน',
        lineStep2: 'ส่งรหัส 6 หลักนี้ให้ Bot',
        expires: 'รหัสหมดอายุใน {time}',
        newCode: 'สร้างรหัสใหม่',
        close: 'ปิด',
        created: 'สร้างสมาชิกแล้ว',
        createFail: 'สร้างสมาชิกไม่สำเร็จ',
        saveFail: 'บันทึกสิทธิ์ไม่สำเร็จ',
        lineFail: 'สร้างรหัส LINE ไม่สำเร็จ',
        unbound: 'ยกเลิกการเชื่อมต่อ LINE แล้ว',
        moduleRequired: 'เลือกอย่างน้อยหนึ่งฟังก์ชัน',
        credentialsRequired: 'กรอกชื่อผู้ใช้และรหัสผ่าน MR.ERP',
        memberScope:
            'สมาชิกเห็นเฉพาะรายการที่ตนเองบันทึก ข้อมูลทั้งหมดอยู่ในร้านและชุดบัญชีของเจ้าของ',
    },
    en: {
        nav: 'Team management',
        title: 'ERP team management',
        subtitle: 'Invite staff and grant only the functions they need.',
        invite: 'Invite member',
        seats: 'Seats',
        sharedQuota: 'OCR credits are shared by the store and topped up by the owner.',
        loading: 'Loading members…',
        emptyTitle: 'No members yet',
        emptyBody: 'Add your first purchasing or sales member.',
        error: 'Could not load the team.',
        retry: 'Try again',
        account: 'Pearnly account',
        password: 'Pearnly password',
        modules: 'Allowed functions',
        product: 'Products',
        purchase: 'Purchasing',
        sales: 'Sales',
        erp: 'Shared ERP target',
        none: 'Do not push to ERP yet',
        existing: 'Owner connection',
        newMrerp: 'Add MR.ERP account',
        mrUser: 'MR.ERP username',
        mrPass: 'MR.ERP password',
        expressHelp:
            'Express uses the account-set mapping scanned by Pearnly Companion, so no username or password is required.',
        noExpress: 'The owner must connect Express and scan an account set in Companion first.',
        cancel: 'Cancel',
        create: 'Create member',
        creating: 'Creating…',
        active: 'Active',
        inactive: 'Disabled',
        save: 'Save access',
        saved: 'Access saved',
        lineBound: 'LINE bound',
        lineUnbound: 'LINE not bound',
        bindLine: 'Bind LINE',
        unbind: 'Unbind',
        erpConnected: 'Uses {name}',
        erpNone: 'No ERP push',
        lastLogin: 'Last login',
        never: 'Never',
        lineTitle: 'Let the member bind their own LINE',
        lineStep1: 'Scan the QR code to add Pearnly ERP.',
        lineStep2: 'Send this 6-digit code to the Bot.',
        expires: 'Code expires in {time}',
        newCode: 'New code',
        close: 'Close',
        created: 'Member created',
        createFail: 'Could not create the member',
        saveFail: 'Could not save access',
        lineFail: 'Could not create a LINE code',
        unbound: 'LINE unbound',
        moduleRequired: 'Select at least one function.',
        credentialsRequired: 'Enter the MR.ERP username and password.',
        memberScope:
            'Members see only records they created. Every record remains in the owner’s store and account set.',
    },
    zh: {
        nav: '团队管理',
        title: 'ERP 团队管理',
        subtitle: '邀请员工，并按岗位授予最小功能权限。',
        invite: '邀请成员',
        seats: '席位',
        sharedQuota: 'OCR 额度由店铺共用并由老板统一充值。',
        loading: '正在加载成员…',
        emptyTitle: '还没有成员',
        emptyBody: '添加第一位采购或销售人员。',
        error: '团队数据加载失败',
        retry: '重试',
        account: 'Pearnly 登录账号',
        password: 'Pearnly 登录密码',
        modules: '允许使用的功能',
        product: '商品',
        purchase: '采购',
        sales: '销售',
        erp: '共用的 ERP 目标',
        none: '暂不推送 ERP',
        existing: '老板已有连接',
        newMrerp: '新增 MR.ERP 账号',
        mrUser: 'MR.ERP 账号',
        mrPass: 'MR.ERP 密码',
        expressHelp: 'Express 复用 Pearnly 小助手扫描的套账映射，不需要账号密码。',
        noExpress: '请老板先接通 Express，并在小助手中扫描套账。',
        cancel: '取消',
        create: '创建成员',
        creating: '正在创建…',
        active: '已启用',
        inactive: '已停用',
        save: '保存权限',
        saved: '权限已保存',
        lineBound: 'LINE 已绑定',
        lineUnbound: 'LINE 未绑定',
        bindLine: '绑定 LINE',
        unbind: '解绑',
        erpConnected: '使用 {name}',
        erpNone: '不推送 ERP',
        lastLogin: '最近登录',
        never: '从未登录',
        lineTitle: '请成员用自己的 LINE 完成绑定',
        lineStep1: '扫描二维码添加 Pearnly ERP 好友。',
        lineStep2: '把这组 6 位绑定码发送给 Bot。',
        expires: '绑定码将在 {time} 后失效',
        newCode: '换一个绑定码',
        close: '关闭',
        created: '成员创建成功',
        createFail: '成员创建失败',
        saveFail: '权限保存失败',
        lineFail: '无法生成 LINE 绑定码',
        unbound: 'LINE 已解绑',
        moduleRequired: '请至少勾选一个功能。',
        credentialsRequired: '请输入 MR.ERP 账号和密码。',
        memberScope: '成员只看到自己录入的记录；所有数据仍落在老板的店铺和套账内。',
    },
    ja: {
        nav: 'チーム管理',
        title: 'ERP チーム管理',
        subtitle: 'スタッフを招待し、必要最小限の機能だけを付与します。',
        invite: 'メンバーを招待',
        seats: '席',
        sharedQuota: 'OCR クレジットは店舗で共有し、オーナーがチャージします。',
        loading: 'メンバーを読み込み中…',
        emptyTitle: 'メンバーはいません',
        emptyBody: '仕入または販売担当者を追加します。',
        error: 'チームを読み込めませんでした',
        retry: '再試行',
        account: 'Pearnly アカウント',
        password: 'Pearnly パスワード',
        modules: '利用できる機能',
        product: '商品',
        purchase: '仕入',
        sales: '販売',
        erp: '共有 ERP 接続先',
        none: 'ERP へ送信しない',
        existing: 'オーナーの接続',
        newMrerp: 'MR.ERP アカウントを追加',
        mrUser: 'MR.ERP ユーザー名',
        mrPass: 'MR.ERP パスワード',
        expressHelp:
            'Express は Pearnly Companion が読み取った帳簿マッピングを使用するため、ユーザー名とパスワードは不要です。',
        noExpress: '先にオーナーが Express を接続し、Companion で帳簿を読み取ってください。',
        cancel: 'キャンセル',
        create: 'メンバーを作成',
        creating: '作成中…',
        active: '有効',
        inactive: '無効',
        save: '権限を保存',
        saved: '保存しました',
        lineBound: 'LINE 連携済み',
        lineUnbound: 'LINE 未連携',
        bindLine: 'LINE を連携',
        unbind: '連携解除',
        erpConnected: '{name} を使用',
        erpNone: 'ERP 送信なし',
        lastLogin: '最終ログイン',
        never: '未ログイン',
        lineTitle: 'メンバー本人の LINE を連携',
        lineStep1: 'QR コードを読み取り Pearnly ERP を友だち追加します。',
        lineStep2: 'この6桁コードを Bot に送信します。',
        expires: '有効期限まで {time}',
        newCode: '新しいコード',
        close: '閉じる',
        created: 'メンバーを作成しました',
        createFail: 'メンバーを作成できませんでした',
        saveFail: '権限を保存できませんでした',
        lineFail: 'LINE 連携コードを作成できませんでした',
        unbound: 'LINE 連携を解除しました',
        moduleRequired: '機能を1つ以上選択してください。',
        credentialsRequired: 'MR.ERP のユーザー名とパスワードを入力してください。',
        memberScope:
            'メンバーが見られるのは自分が登録した記録だけです。すべてのデータはオーナーの店舗と帳簿に保存されます。',
    },
};

export function erpTeamCopy(): ErpTeamCopy {
    const lang = String(window._currentLang || document.documentElement.lang || 'th').slice(0, 2);
    return COPY[lang] || COPY.th;
}

export function fillCopy(template: string, values: Record<string, string>): string {
    return Object.keys(values).reduce(
        (result, key) => result.split(`{${key}}`).join(values[key]),
        template
    );
}
