// 路由表(纯数据 · 从 core-boot 抽出控行数):合法路由 + route → window 加载函数名。
// 加新页只改这里,core-boot 的 routeTo/reloadCurrentRoute 数据驱动不再长。

// v118.32.5.5.37 NAV-IA Phase 5: automation 页面无侧边栏入口且不可路由 · 银行上传改为对账中心原地上传
export const VALID_ROUTES = [
    'dms-intake',
    'dashboard',
    'history',
    'integrations',
    'push-logs',
    'erp-review',
    'templates',
    'api-keys',
    'settings',
    'exceptions',
    'clients',
    'company',
    'vouchers',
    'purchase',
    'purchase-suppliers',
    'purchase-settings',
    'purchase-form',
    'purchase-detail',
    'purchase-export',
    'purchase-capture',
    'sales-invoices',
    'sales-products',
    'expense-data',
    'sales-account',
    'reconcile',
    'cloud',
    'knowledge',
    'inventory',
    'pos-onboarding',
    'sales-report',
    'pos-sales-log',
    'pos-audit',
    'pos-cashiers',
    'pos-tables',
    'pos-payment',
    'pos-sheets',
    'acct-review',
    'acct-accounts',
    'acct-settings',
    'acct-bank',
    'acct-manual',
    'acct-books',
    'tax-center',
    'tax-pp30',
    'tax-pnd',
    'tax-settings',
];

// Phase3 入口守卫(各是各的 · 纯 UX 层)· 壳专属路由集。跨壳深链——pos-entry 手敲会计路由 /
// main-entry 手敲纯 POS 路由——回落到当前入口首页(FIRM→dashboard,POS→inventory)。两壳共用路由
// (clients/company/products/采购/销售/dashboard/settings 等)不列 = 中性放行。后端
// services/authz/deps._check 才是真边界,此处只减少用户误入空壳的摩擦。
export const POS_ENTRY_ROUTES = new Set<string>([
    'inventory',
    'sales-report',
    'pos-sales-log',
    'pos-audit',
    'pos-cashiers',
    'pos-tables',
    'pos-payment',
    'pos-sheets',
    'pos-onboarding',
]);

export const MAIN_ENTRY_ROUTES = new Set<string>([
    'vouchers',
    'acct-review',
    'acct-accounts',
    'acct-settings',
    'acct-bank',
    'acct-manual',
    'acct-books',
    'tax-center',
    'tax-pp30',
    'tax-pnd',
    'tax-settings',
    'dms-intake',
    'history',
    'push-logs',
    'reconcile',
    'exceptions',
    'integrations',
    'templates',
    'api-keys',
]);

// route → 页面加载函数名(window.*)· routeTo 进路由即调。数据驱动替原 if 链。
export const ROUTE_LOADERS: Record<string, string> = {
    settings: 'renderSettings',
    'dms-intake': 'loadDmsIntake',
    history: 'loadHistoryPage',
    'push-logs': 'loadPushLogs',
    'erp-review': 'loadErpReview',
    clients: 'loadClientsPage',
    company: 'loadCompanyProfile',
    knowledge: 'loadKnowledgePage',
    inventory: 'loadInventoryPage',
    'pos-onboarding': 'loadPosOnboardingPage',
    'sales-report': 'loadSalesReport',
    'pos-sales-log': 'loadPosSalesLog',
    'pos-audit': 'loadPosAudit',
    'pos-cashiers': 'loadPosCashiers',
    'pos-tables': 'loadPosTables',
    'pos-payment': 'loadPosPayment',
    'pos-sheets': 'loadPosSheets',
    'sales-invoices': 'loadSalesWorkbench',
    'sales-products': 'loadSalesProducts',
    'expense-data': 'loadExpenseData',
    'sales-account': 'loadSalesAccount',
    purchase: 'loadPurchaseList',
    'purchase-suppliers': 'loadPurchaseSuppliers',
    'purchase-settings': 'loadPurchaseSettings',
    'purchase-form': 'loadPurchaseForm',
    'purchase-detail': 'loadPurchaseDetail',
    'purchase-export': 'loadPurchaseExport',
    'purchase-capture': 'loadPurchaseCapture',
    exceptions: 'loadExceptionsPage',
    reconcile: 'loadReconcilePage',
    dashboard: 'loadDashboard',
    vouchers: 'loadAcctList',
    'acct-review': 'loadAcctReview',
    'acct-accounts': 'loadAcctAccounts',
    'acct-settings': 'loadAcctSettings',
    'acct-bank': 'loadAcctBank',
    'acct-manual': 'loadAcctManual',
    'acct-books': 'loadAcctBooks',
    'tax-center': 'loadTaxCenter',
    'tax-pp30': 'loadTaxPp30',
    'tax-pnd': 'loadTaxPnd',
    'tax-settings': 'loadTaxSettings',
};
