// 路由表(纯数据 · 从 core-boot 抽出控行数):合法路由 + route → window 加载函数名。
// 加新页只改这里,core-boot 的 routeTo/reloadCurrentRoute 数据驱动不再长。

// v118.32.5.5.37 NAV-IA Phase 5: automation 页面无侧边栏入口且不可路由 · 银行上传改为对账中心原地上传
export const VALID_ROUTES = [
    'dms-intake',
    'dashboard',
    'history',
    'integrations',
    'templates',
    'api-keys',
    'settings',
    'exceptions',
    'clients',
    'company',
    'vouchers',
    'purchase',
    'purchase-suppliers',
    'purchase-settings',
    'purchase-inbox',
    'purchase-form',
    'purchase-detail',
    'purchase-export',
    'sales-invoices',
    'sales-products',
    'sales-account',
    'receivables',
    'reconcile',
    'cloud',
    'knowledge',
    'inventory',
    'pos-onboarding',
    'sales-report',
    'pos-cashiers',
    'pos-tables',
    'pos-payment',
    'acct-review',
    'acct-accounts',
    'acct-settings',
    'acct-bank',
    'acct-manual',
    'acct-books',
    'tax-center',
    'tax-pp30',
    'tax-pnd',
    'tax-settings',
];

// route → 页面加载函数名(window.*)· routeTo 进路由即调。数据驱动替原 if 链。
export const ROUTE_LOADERS: Record<string, string> = {
    settings: 'renderSettings',
    'dms-intake': 'loadDmsIntake',
    history: 'loadHistoryPage',
    clients: 'loadClientsPage',
    company: 'loadCompanyProfile',
    knowledge: 'loadKnowledgePage',
    inventory: 'loadInventoryPage',
    'pos-onboarding': 'loadPosOnboardingPage',
    'sales-report': 'loadSalesReport',
    'pos-cashiers': 'loadPosCashiers',
    'pos-tables': 'loadPosTables',
    'pos-payment': 'loadPosPayment',
    'sales-invoices': 'loadSalesWorkbench',
    'sales-products': 'loadSalesProducts',
    'sales-account': 'loadSalesAccount',
    purchase: 'loadPurchaseList',
    'purchase-suppliers': 'loadPurchaseSuppliers',
    'purchase-settings': 'loadPurchaseSettings',
    'purchase-inbox': 'loadPurchaseInbox',
    'purchase-form': 'loadPurchaseForm',
    'purchase-detail': 'loadPurchaseDetail',
    'purchase-export': 'loadPurchaseExport',
    exceptions: 'loadExceptionsPage',
    reconcile: 'loadReconcilePage',
    dashboard: 'loadDashboard',
    vouchers: 'loadAcctList',
    'acct-review': 'loadAcctReview',
    'acct-accounts': 'loadAcctAccounts',
    'acct-settings': 'loadAcctSettings',
    'acct-bank': 'loadAcctBank',
    'acct-manual': 'loadAcctManual',
    'acct-books': 'loadAcctBooks',
    'tax-center': 'loadTaxCenter',
    'tax-pp30': 'loadTaxPp30',
    'tax-pnd': 'loadTaxPnd',
    'tax-settings': 'loadTaxSettings',
};
