# -*- coding: utf-8 -*-
"""真库冒烟(test_*_pg_smoke.py)共用的连库口。

CI 的 pg-smoke job 按这个文件名 glob 收人(见 .github/workflows/ci.yml),新写一份 smoke
不用登记就自动进闸 —— 正因为进得这么容易,"连哪个库"必须只有一处答案:

  · 只认 PEARNLY_PG_SMOKE_URL,取不到回落 docker-compose.yml 里 pearnly-db 的本地 DSN;
  · **绝不回落 DATABASE_URL** —— 开发机上那个变量指的是生产库,而 smoke 会真建表真删行。

连不上就整类 skip(CI 侧另有「skip 也算红」的判据兜着,本机没起 docker 时才是真 skip)。
建表 / 清表 / 游标替身各家不同(并发用例要每路一条独立连接,别家共用一条),留在各自文件里。
"""

from __future__ import annotations

import os
import unittest

LOCAL_DSN = os.environ.get(
    "PEARNLY_PG_SMOKE_URL", "postgresql://pearnly:pearnly_local_dev@localhost:5432/pearnly"
)


def connect():
    # psycopg2 延到调用时才 import:没装驱动的机器上,收集用例这一步不该直接崩。
    import psycopg2

    return psycopg2.connect(LOCAL_DSN, connect_timeout=3)


def connect_or_skip():
    """连得上返回连接;连不上抛 SkipTest(setUpClass 里直接调)。"""
    try:
        return connect()
    except Exception as exc:
        raise unittest.SkipTest(f"本地 pearnly-db 不可达({exc!r})· 起 docker compose 后再跑")


def require_disposable_db(cur, schema: str, expected_prefix: str) -> None:
    """Prove destructive smoke cleanup is scoped to its task-owned schema."""
    if not schema or schema == "public" or not schema.startswith(expected_prefix):
        raise RuntimeError(
            f"refusing destructive cleanup for non-task schema {schema!r} "
            f"(expected prefix {expected_prefix!r})"
        )
    cur.execute(
        "SELECT current_schema() AS current_schema, to_regnamespace(%s) AS namespace",
        (schema,),
    )
    row = cur.fetchone()
    current_schema = row.get("current_schema") if hasattr(row, "get") else row[0]
    namespace = row.get("namespace") if hasattr(row, "get") else row[1]
    if current_schema != schema or namespace is None:
        raise RuntimeError(f"refusing destructive cleanup outside current task schema {schema!r}")


PUBLIC_ROUTINE_NAMES = (
    "preserve_managed_erp_endpoints_on_user_delete",
    "prevent_managed_erp_endpoint_creator_change",
    "purge_managed_erp_endpoints_for_users",
    "erp_endpoint_has_legacy_activity",
    "guard_erp_endpoint_enrollment_columns",
)


def quote_identifier(value: str) -> str:
    """Quote an identifier generated by this smoke test, never external SQL."""
    if not value or "\x00" in value:
        raise ValueError("SQL identifier must be non-empty and NUL-free")
    return '"' + value.replace('"', '""') + '"'


def schema_function(schema: str, name: str, arguments: str = "") -> str:
    return f"{schema_function_name(schema, name)}({arguments})"


def schema_function_name(schema: str, name: str) -> str:
    return f"{quote_identifier(schema)}.{quote_identifier(name)}"


def snapshot_public_routines(cur) -> dict[tuple[str, str], tuple[int, str]]:
    """Capture public routine identity and definition before disposable DDL."""
    cur.execute(
        "SELECT p.proname, pg_get_function_identity_arguments(p.oid) AS arguments, "
        "p.oid::bigint AS oid, md5(pg_get_functiondef(p.oid)) AS definition_hash "
        "FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace "
        "WHERE n.nspname = 'public' AND p.proname = ANY(%s) "
        "ORDER BY p.proname, arguments",
        (list(PUBLIC_ROUTINE_NAMES),),
    )
    return {
        (row["proname"], row["arguments"]): (row["oid"], row["definition_hash"])
        for row in cur.fetchall()
    }


def assert_public_routines_unchanged(cur, expected: dict[tuple[str, str], tuple[int, str]]) -> None:
    actual = snapshot_public_routines(cur)
    if actual != expected:
        raise AssertionError(
            f"public managed routine catalog changed: expected={expected!r} actual={actual!r}"
        )
